#!/usr/bin/env python3
"""Extract the PRG32 firmware 8x8 font for the host test framebuffer.

The cartridge itself never embeds a font: it calls prg32_gfx_text8(). The
host tests (tests/host/host_prg32.h) need the same glyphs to render
screenshots that match the firmware, so this tool copies them from
$PRG32_REPO/components/prg32/prg32_display_qemu_rgb.c (default ../PRG32)
into tests/host/font8.h. The font is part of PRG32 (MIT, PRG32
contributors). The output is committed, so tests run without regenerating.
"""
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRG32 = Path(os.environ.get("PRG32_REPO", ROOT.parent / "PRG32"))


def main() -> None:
    src = (PRG32 / "components/prg32/prg32_display_qemu_rgb.c").read_text(encoding="utf-8")
    body = re.search(r"static const uint8_t g_font8\[96\]\[8\][^=]*=\s*\{(.*?)\n\};", src, re.S).group(1)
    glyphs = {}
    for m in re.finditer(r"\[\s*'(\\.|[^'])'\s*-\s*32\s*\]\s*=\s*\{([^}]*)\}", body):
        ch = m.group(1)[-1] if m.group(1).startswith("\\") else m.group(1)
        glyphs[ord(ch)] = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]+)", m.group(2))]
    missing = [chr(c) for c in range(32, 127) if c not in glyphs or len(glyphs[c]) != 8]
    if missing:
        raise SystemExit(f"font glyphs missing: {missing}")
    out = [
        "/* Generated by tools/build_font.py from the PRG32 firmware font (MIT).",
        " * ASCII 32..126, 8x8, most significant bit = leftmost pixel. */",
        "#ifndef DF_HOST_FONT8_H",
        "#define DF_HOST_FONT8_H",
        "",
        "static const unsigned char host_font8[95][8] = {",
    ]
    for c in range(32, 127):
        label = {"\\": "backslash", "*": "star", "/": "slash"}.get(chr(c), chr(c))
        out.append("    {" + ", ".join(f"0x{v:02x}" for v in glyphs[c]) + f"}}, /* {label} */")
    out += ["};", "", "#endif", ""]
    (ROOT / "tests/host/font8.h").write_text("\n".join(out), encoding="utf-8")
    print("tests/host/font8.h: 95 glyphs")


if __name__ == "__main__":
    main()
